# Generated by Django 3.1.5 on 2021-02-08 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('general', 'General'), ('groceries', 'Groceries'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('eating_out', 'Eating Out'), ('personal_care', 'Personal Care'), ('charity', 'Charity'), ('savings', 'Savings'), ('gifts', 'Gifts'), ('transport', 'Transport'), ('holiday', 'Holiday'), ('family', 'Family'), ('debt', 'Debt'), ('bills', 'Bills'), ('finances', 'Finances'), ('fuel', 'Fuel')], default='general', max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(verbose_name='date')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.sheet')),
            ],
        ),
    ]
