# Generated by Django 3.1.5 on 2021-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
